### ISSUE TITLE
TeX derivation differs from code

### ISSUE THREAD

**Issue by jmemich** [jmemich/matrix_factorization#4]
[Derivation](https://github.com/jmemich/matrix_factorization/blob/46eb5c2b723bdb0c15fe0b2f40217fcc89cd0927/matrix_factorization.tex#L101-L104) of update rule with regularization is:
![image](https://user-images.githubusercontent.com/7613058/27865983-4437c588-615a-11e7-91c9-7b9e815e399b.png)
But [code](https://github.com/jmemich/matrix_factorization/blob/46eb5c2b723bdb0c15fe0b2f40217fcc89cd0927/mf.cpp#L23-L30) is:
```cpp
float eij = R(row,col)-P.row(row).dot(Q.col(col));
for (int k=0; k<K; k++) {
    float reg_p = (lambda*Q.row(k)).sum();
    float reg_q = (lambda*P.col(k)).sum();
    float p_=P(row,k)+2*alpha*((Q.row(k)*eij).sum()-reg_p);
    float q_=Q(k,col)+2*alpha*((P.col(k)*eij).sum()-reg_q);
    P(row,k) = p_;
    Q(k, col) = q
````
@xdavio any idea what I fucked up here?

**Comment by xdavio** [comment]
double check [this line](https://github.com/jmemich/matrix_factorization/blob/master/matrix_factorization.tex#L78)
